import 'jest-canvas-mock';
import ResizeObserver from 'resize-observer-polyfill';
import renderer, { act } from 'react-test-renderer';
import { maskRegex, maskUuid } from '../../helpers/snapshot-tests-masking';
import React from 'react';
import { dataset0 } from '../../helpers/snapshot-tests-data';
import { VariantInternationalComparisonChart } from '../VariantInternationalComparisonChart';

window.ResizeObserver = ResizeObserver;

describe('<VariantInternationalComparisonChart>', () => {
  it('dataset0 renders correctly', async () => {
    const { variantInternationalDateCount, wholeInternationalDateCount } = dataset0;
    const tree = renderer.create(
      <VariantInternationalComparisonChart
        preSelectedCountries={['Germany']}
        variantInternationalSampleSet={variantInternationalDateCount}
        wholeInternationalSampleSet={wholeInternationalDateCount}
      />
    );
    await act(async () => {});
    const snapshot = tree.toJSON();
    maskUuid(snapshot);
    maskRegex(snapshot, /css-[0-9a-z]+/gi); // Mask weird css class names generated by react-select
    expect(snapshot).toMatchSnapshot();
  });
});
