import 'jest-canvas-mock';
import ResizeObserver from 'resize-observer-polyfill';
import { maskRegex } from '../../helpers/testing/snapshot-tests-masking';
import React from 'react';
import { dataset0 } from '../../helpers/testing/snapshot-tests-data0';
import { VariantInternationalComparisonChart } from '../VariantInternationalComparisonChart';
import { renderAndWaitToMatchSnapshot } from '../../helpers/testing/renderAndWaitToMatchSnapshot';

window.ResizeObserver = ResizeObserver;
vi.mock('recharts');

describe('<VariantInternationalComparisonChart>', () => {
  it('dataset0 renders correctly', async () => {
    const { variantInternationalDateCount, wholeInternationalDateCount } = dataset0;

    await renderAndWaitToMatchSnapshot(
      <VariantInternationalComparisonChart
        preSelectedCountries={['Germany']}
        variantInternationalSampleSet={variantInternationalDateCount}
        wholeInternationalSampleSet={wholeInternationalDateCount}
      />,
      renderedJson => {
        maskRegex(renderedJson, /css-[0-9a-z]+/gi); // Mask weird css class names generated by react-select
      }
    );
  });
});
